title:
    vi: Nguyên Tiêu Náo Hoa Đăng
summary:
    vi: Đây là một hoạt động phổ biến rất rộng rãi trong dân gian Trung Hoa cổ đại, tiết Nguyên Tiêu xem đèn thưởng thức cảnh đẹp về đêm, náo nhiệt nhất là vào ngày mồng một tháng một. Thôn Quân Tề thành phố Tân Tập tỉnh Hà Bắc là một nơi ở bình nguyên phía bắc Trung Hoa, hội đèn Nguyên Tiêu đã trở thành tập tục của toàn thôn. Vào ngày này, nam nữ lão ấu tay cầm các loại lồng đèn dọc ngang các đường phố, ánh lửa của ngọn đèn luôn bên cạnh tiếng cười nói, tràn đầy khắp thôn trang.
icon:
img: '{"s":"entry-img-s.jpg","v":"entry-img-v.jpg","h":"entry-img-h.jpg"}'
file:
    vi: index-vi.md
tags:
    vi: [Nguyên Tiêu]
tc: 1420561225
tu: 1421037767
