title:
    vi: Hải Nam Cổ Miếu Cà Mau - Ngoại cảnh
summary:
    vi: Hải Nam Cổ Miếu Cà Mau - Ngoại cảnh
icon:
img: '{"s":"entry-img-s.jpg","v":"entry-img-v.jpg","h":"entry-img-h.jpg"}'
file:
    vi: index-vi.md
tags:
    vi: [cổ miếu]
tc: 1518994856
tu: 1518998137
