title:
    vi: Tiền Quyên Góp Cất Lại Chùa Hải Nam (2)
summary:
    vi: TIỀN QUYÊN GÓP CẤT LẠI CHÙA HẢI NAM (Ngày khởi công) (ĐỢT II)
icon:
img: '{"s":"entry-img-s.jpg","v":"entry-img-v.jpg","h":"entry-img-h.jpg"}'
file:
    vi: index-vi.md
tags:
    vi: [quyên tiền]
tc: 1459702441
tu: 1459707402
