title:
    vi: Tiền Quyên Góp Cất Lại Chùa Hải Nam (1)
summary:
    vi: TIỀN QUYÊN GÓP CẤT LẠI CHÙA HẢI NAM (trước ngày khởi công) (ĐỢT I)
icon:
img: '{"s":"entry-img-s.jpg","v":"entry-img-v.jpg","h":"entry-img-h.jpg"}'
file:
    vi: index-vi.md
tags:
    vi: [quyên tiền]
tc: 1459697777
tu: 1459698201
