title:
    vi: Hải Nam Cổ Miếu Cà Mau - Ngày giỗ 15 tháng 6 âm lịch 108 vị anh linh
summary:
    vi: Hải Nam Cổ Miếu Cà Mau - Ngày giỗ 15 tháng 6 âm lịch 108 vị anh linh
icon:
img: '{"s":"entry-img-s.jpg","v":"entry-img-v.jpg","h":"entry-img-h.jpg"}'
file:
    vi: index-vi.md
tags:
    vi: [giỗ]
tc: 1658002591
tu: 1658002591
