title:
    vi: Đấu đèn quyên tiền trùng kiến miếu Hải Nam
summary:
    vi: Biên bản Đấu đèn quyên tiền trùng kiến miếu HẢI NAM
icon:
img: '{"s":"entry-img-s.jpg","v":"entry-img-v.jpg","h":"entry-img-h.jpg"}'
file:
    vi: index-vi.md
tags:
    vi: [quyên tiền]
tc: 1459693385
tu: 1459718530
