title:
    vi: Tiền Quyên Góp Cất Lại Chùa Hải Nam (3)
summary:
    vi: TIỀN QUYÊN GÓP CẤT LẠI CHÙA HẢI NAM (Sau ngày khởi công) (ĐỢT III)
icon:
img: '{"s":"entry-img-s.jpg","v":"entry-img-v.jpg","h":"entry-img-h.jpg"}'
file:
    vi: index-vi.md
tags:
    vi: [quyên tiền]
tc: 1459709504
tu: 1459713833
