title:
    vi: Trùng kiến Hải Nam Cổ Miếu
summary:
    vi: Nguyên Hải Nam Cổ Miếu (Miếu Cô Hồn) Cà Mau đã được bà con người Hải Nam xây dựng trên 150 năm trước đây. Đến năm 1975, do tình hình kinh tế xã hội của đất nước thay đổi, bà con người Hải Nam cũng giảm đi, miếu thiếu người trông nom nên hư hỏng nặng.
icon:
img: '{"s":"entry-img-s.jpg","v":"entry-img-v.jpg","h":"entry-img-h.jpg"}'
file:
    vi: index-vi.md
tags:
tc: 1420990583
tu: 1459167036
