title:
    vi: Hải Nam Cổ Miếu Cà Mau - Nội thất
summary:
    vi: Hải Nam Cổ Miếu Cà Mau - Nội thất
icon:
img: '{"s":"entry-img-s.jpg","v":"entry-img-v.jpg","h":"entry-img-h.jpg"}'
file:
    vi: index-vi.md
tags:
    vi: [cổ miếu]
tc: 1518998682
tu: 1518998822
