title:
    vi: Lễ Vía 108 Vị Chiêu Ứng Công Anh Liệt
summary:
    vi: Lễ Vía 108 Vị Chiêu Ứng Công Anh Liệt
icon:
img: '{"s":"entry-img-s.jpg","v":"entry-img-v.jpg","h":"entry-img-h.jpg"}'
file:
    vi: index-vi.md
tags:
    vi: ["vía", "108"]
tc: 1690978934
tu: 1690978934
