name: hainamcomieu

on:
  # Automatically trigger it when detected changes in repo
  pull_request:
    branches: [ master ]
    types: [ closed ]

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HAINAMCOMIEU_AZURE_CREDENTIALS }}
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.HAINAMCOMIEU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HAINAMCOMIEU_REGISTRY_PASSWORD }}
          containerAppName: hainamcomieu
          resourceGroup: btnguyen2k
          imageToBuild: btnguyen2k/hainamcomieu:${{ github.sha }}
